### ISSUE TITLE
How to deserialize data structures which type is not known ahead of time?

### ISSUE THREAD

**Issue by Arugin** [hadashiA/VYaml#126]
I have the following data structure:

```yaml
archetypes:
- types:
  - Type.Position
  - Type.Intensity
  - Type.Guid  
  components:
  - - value:
        x: 3
        y: 2
        z: 12
    - value:
        x: -3
        y: 73
        z: 1
    - value:
        x: 1
        y: 1
        z: 1
    - value:
        x: 5
        y: 5
        z: 3    
  - - value: 0.5
    - value: 0.0015
    - value: 0.001
    - value: 0.1  
  - - value: 80f91c84-504b-444f-b328-730ada871d22
    - value: 0c84c341-257f-4c90-9b02-eb224c5be9f4
    - value: c3410c84-257f-4c90-9b02-eb224c5be9f4
    - value: 0c84c341-257f-4c90-9b02-eb224c5be9f4
  otherData:
  ...
- types:
    ...
  components:
    ...
```
Types array can contain any type implementing a specific interface, that can't be known ahead of time. It can also cantain any number of types. Each array in the components contains data corresponding to that type. The sizes of components arrays will always match.

I need to deserialize this data using custom deserializer and get a set of arrays with that data.

When using Newtosoft.Json I can do something like this:
 
```csharp
Array[] arrays = new Array[types.Length];
for(int i = 0; i < currTypes.Length; i++) {
 var currType = types[i].ToObject<Type>(); 

 arrays[i] = (Array)components[sourceIndex].ToObject(currType.type.MakeArrayType());
 if (array[i].Length == 0) {
	 arrays[i] = Array.CreateInstance(currType.type, count);
 }
}
```

And then I can pass this data further and work with that. Context: it is scene serialization for game engine, where scene structure and set of used components depends on user and can't be known ahead of time.

It looks like there is no way to deserialize something using VYaml when data types are not known ahead of time, or am I missing something? Do you plan to add overloads of context.Deserialize methods, that will get Type as a second parameter?
