### ISSUE TITLE
Error when parsing empty scalar in a sequence

### ISSUE THREAD

**Issue by UlyssesWu** [hadashiA/VYaml#32]
```yaml
_Ulysses:
  propertyKey: _Test
  enable: 0
  value: 0
  keywords:
  - 
  - _RIDE_ON
  - _COME_ON
```

This YAML cannot be parsed in VYaml but is valid.
