### ISSUE TITLE
It's not possible to serialize derrived type without any parameters

### ISSUE THREAD

**Issue by nicloay** [hadashiA/VYaml#57]
If I have 2 types like Type1 and Type2 which implement a common interface it's not possible to deserialize document if one of them has no  extra parameters
```
list:
  - !type1
    param: 9999
  - !type2
  - !type1
    param: 3333
```

as type2 doesn't have parameter the result list will have only 2 elements of type1
